### ISSUE TITLE
layout-header.less - Remove custom variables

### ISSUE THREAD

**Issue by dominic-hickey** [basekit-templates/trivia#1]
#### 'layout-header.less' (lines 6-9)

https://github.com/basekit-templates/trivia/blob/develop/less/layout-header.less#L6-L9

Can you remove the custom variables used in this file - this is inherited from a v1 theme. As they are not reused too often they're not necessary. We also want to make sure that we use the same variables in all v2 themes.

**Comment by dominic-hickey** [comment]
* [ ] Testing

**Comment by daviddarnes** [comment]
:star2:

**Comment by dominic-hickey** [comment]
You also need to remove the CSS that uses the variables - replace them with the original values!

**Comment by daviddarnes** [comment]
Commit message `Removes unused variables - Fixes #1`
